/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afis;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefanos Tzortzoglou
 */
public class FormAlternative extends javax.swing.JFrame {

    /**
     * Creates new form FormAlternative
     */
    public FormAlternative() {
        initComponents();
        this.setLocationRelativeTo(null);
        Clock obj = new Clock(labelTime);
        obj.start();
    }
    
        public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Resources/icon.png"));
        return retValue;
    }
    
    //Validate Username and Password
    public boolean validate(String name, String pass){
           
        String qSql = "SELECT strUsername, pssPassword "
                + "FROM tblemployee "
                + "WHERE strUsername ='" + name + "' AND pssPassword ='" + pass +"'";
        
        int cont = 0;
        
        //Connection to the DB
        ConnectionMySQL mysql = new ConnectionMySQL();
        Connection con = mysql.Connect();
        
        try{
            Statement st = con.createStatement();
            //Object that containts the results of the search
            ResultSet rs = st.executeQuery(qSql);
            
            while(rs.next()){
                cont = cont + 1;
            }
                                               
        } catch(SQLException ex){
        }
        
        if(cont == 1){
                return true;
            }else{
                return false;
            }    
    }    
       
    private Integer getName(String emp){
        int name = 0;
        
        //Connection variables
        ConnectionMySQL mysql = new ConnectionMySQL();
        Connection con = mysql.Connect();
        
        String qSql = "SELECT (idEmployee) AS ID "
                + "FROM tblemployee "
                + "WHERE strUsername ='" + emp + "'";
        
        try{
            PreparedStatement identificationStmt = con.prepareStatement(qSql);
            ResultSet rs = identificationStmt.executeQuery();

            //If the name is found in the DB
            while(rs.next()){
                name = rs.getInt("ID");
            }
            
        }catch(Exception ex){
        }
        
        return name;
    }
    
    
    public void recordAttendance(){
        //Connection variables
        ConnectionMySQL mysql = new ConnectionMySQL();
        Connection con = mysql.Connect();
        
        //Variables
        String qSql;
        int nd, emple;
                          
        emple = getName(txtUser.getText());
        
        qSql = "INSERT INTO tblattendance(idEmployee, dteDate, tmeTime)"
                + " VALUES(?,current_date(),current_time())";
        
        String rec = "Recorded Attendance";
                 
        try {
            PreparedStatement pst = con.prepareStatement(qSql);
            
            //Insert the value in the field of the DB.
            pst.setInt(1, emple);
            
            nd = pst.executeUpdate();
            
            if(nd > 0){
                JOptionPane.showMessageDialog(null, rec, "Attendance Tracker", 1);
                
            }
            
        } catch (SQLException ex) {
        }
                
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        pssPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check In");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(789, 444));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Attendance Tracker");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 310, 48);

        btnCheck.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(255, 255, 255));
        btnCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fontButton0.png"))); // NOI18N
        btnCheck.setText("Check In");
        btnCheck.setBorder(null);
        btnCheck.setBorderPainted(false);
        btnCheck.setContentAreaFilled(false);
        btnCheck.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheck);
        btnCheck.setBounds(290, 250, 70, 29);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 170, 90, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 210, 75, 25);

        txtUser.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.add(txtUser);
        txtUser.setBounds(260, 170, 130, 29);

        pssPass.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jPanel1.add(pssPass);
        pssPass.setBounds(260, 210, 130, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/administrator2-128.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 150, 128, 128);

        labelTime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(labelTime);
        labelTime.setBounds(50, 70, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed

        String user = txtUser.getText();
        String pass = pssPass.getText();

        if(validate(user,pass) == true){
            recordAttendance();
            txtUser.setText("");
            pssPass.setText("");
            txtUser.requestFocus();
        }else if(validate(user,pass) == false){
            JOptionPane.showMessageDialog(null, "The username or password are not correct");
            txtUser.setText("");
            pssPass.setText("");
            txtUser.requestFocus();
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        AFIS obj = new AFIS();
        obj.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAlternative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAlternative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAlternative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAlternative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlternative().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTime;
    private javax.swing.JPasswordField pssPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
